Better install.md & gitignore
GassaFM/interpr pull request #41
Opened 2024-03-15 14:54 UTC by MaximilianYan

Fixed tree-structure of install.md

old structure:
- Installation
- - Windows
- - Linux
- - macOS
- - Compiling the source

new structure:
- **Installation**
- - - Option for direct download (Windows only)
- - Installing the compiler
- - - Windows
- - - Linux
- - - macOS
- - Compiling the source ;

Add build directory to .gitignore;

2024-03-16 14:20 UTC, GassaFM commented on .gitignore
> +build
А это зачем? У меня после `dub build` появляется не `build`, а `.dub`. В другой системе не так?

2024-03-16 14:21 UTC, GassaFM commented on install.md
> +For **Windows** there is an executable file available on https://github.com/GassaFM/interpr/releases / Assets / interpr-*X.X*-win32.zip (where *X.X* means last release version).
Нужно лучше перевести (сейчас русский порядок слов и русские знаки препинания).

2024-03-16 14:21 UTC, GassaFM commented on install.md
> +## Compiling the sources
неважно, но пусть будет

2024-03-16 14:22 UTC, GassaFM commented on install.ru.md
> +## Установка компилятора
Вот здесь надо яснее сказать, что это установка компилятора D -- а не компилятора Pr, как можно подумать по тому, зачем мы вообще что-то делаем.

2024-03-21 12:22 UTC, MaximilianYan commented on .gitignore
> +build
У меня после `dub build` *interpr.exe* и *interpr.pdb* появляются в корне, so я их направляю в `build`, потому что это интуитивно

2024-04-06 13:19 UTC, GassaFM requested changes
the commit https://github.com/GassaFM/interpr/pull/41/commits/ec287806640e8c52ec71c2df89af5121f2d6da62 should be removed, the PR can be merged then

2024-04-06 13:19 UTC, GassaFM commented on install.ru.md
> +## Установка компилятора
(у Pr не компилятор, а интерпретатор, но на этой стадии читателю не до тонкой разницы)

2024-04-06 13:19 UTC, GassaFM commented on .gitignore
> +build
Причину можно понять, но она не выглядит как повод для коммита в общий репозиторий.

2024-04-06 13:19 UTC, GassaFM commented on .gitignore
> +build
В общем, нужно убрать эту строчку, потому что объективные причины ей добавить непонятны.

И, опять же, better install.md это одна тема, а gitignore другая. Один PR &mdash; одна тема, а не пакетом всё. Особенно если спорно.

Почему так &mdash; как раз видно на примере этого PR. Лучше было бы уже давно за-merge-ить 3 из 4 изменений, чем подвесить всё из-за непонятного момента, который к тому же не относится к теме.

2024-04-06 14:30 UTC, merged