Fix incorrect examples
GassaFM/interpr pull request #45
Opened 2024-03-21 21:26 UTC by MaximilianYan

Solves #43

2024-03-23 10:04 UTC, GassaFM commented on examples/all.pr
>  	x:=array(n)
Всё неплохо, но вот этот `x` и верхний `x_array` я бы переназвал одним и тем же именем, но другим. Например, `a`.

2024-03-25 01:51 UTC, MaximilianYan commented on examples/all.pr
>  	x:=array(n)
Не совсем понял, почему комментарий к строкам 34~38, видимо, очетяпка.

Что касается имён массивов, полагаю, решение будет зависеть от разрешения недокументированной особенности языка, поднятой в #47.

2024-03-25 01:54 UTC, MaximilianYan commented on examples/all.pr
>  	x:=array(n)
> Не совсем понял, почему комментарий к строкам 34~38, видимо, очетяпка.

Понял, кажется, причина в разнице нумераций строк в старой и новой версии *examples/all.pr*.

2024-03-25 11:29 UTC, MaximilianYan commented on examples/all.pr
>  	x:=array(n)
> Всё неплохо, но вот этот `x` и верхний `x_array` я бы переназвал одним и тем же именем, но другим. Например, `a`.

done

2024-03-25 11:30 UTC, MaximilianYan commented
Add namesakes examples and documentation.

2024-03-25 11:31 UTC, MaximilianYan commented
Add namesakes examples and documentation according to #47.

2024-03-25 12:03 UTC, GassaFM reviewed
1. Мы ещё не выяснили даже, баг это или фича.
2. Даже если это фича, отдельный вопрос &mdash; стоит ли она лишнего абзаца в readme &mdash; который занимает время при рассказе на паре.
3. Так что этот коммит явно не в этот pull request.

2024-03-25 12:05 UTC, GassaFM commented
ну и смысл в разных namespace (пространство имён), а не в одинаковых namesake (тёзка)

2024-03-25 12:11 UTC, MaximilianYan commented
> 1. Мы ещё не выяснили даже, баг это или фича.

Извините, я подумал, что вот это:

2024-03-25 12:13 UTC, MaximilianYan commented
> 1. Мы ещё не выяснили даже, баг это или фича.

Извините, я подумал, что вот это —

> In the current version of the language, there are two variable types: int64 and array of int64. In the current implementation, these two are kept in separate namespaces, see struct Context at https://github.com/GassaFM/interpr/blob/master/source/runner.d#L65-L72 and around. The rationale is that the type can be uniquely determined at site of usage, so why bother distinguishing?
> 
> So, what are the benefits and the drawbacks, and what should be done about it, if anything?

— это указание на то, что переменные-тёзки — это намеренное (возможно не намеренное, но, как минимум, корректное и последовательное) явление в языке.

2024-03-25 12:21 UTC, MaximilianYan commented
> ну и смысл в разных namespace (пространство имён), а не в одинаковых namesake (тёзка)

Да, явление возникает из-за изолированных пространств имён под капотом языка, но для пользователя это выглядит как две переменные с идентичными именами, которые можно различить только подобно различению перегруженных функций в c++. Я подумал, что явление подобной перегрузки переменной будет интуитивно назвать переменными-тёзками.

2024-03-25 22:54 UTC, MaximilianYan commented
> 2\. Даже если это фича, отдельный вопрос — стоит ли она лишнего абзаца в readme — который занимает время при рассказе на паре.

Вопрос очень тонкий. Он, казалось бы, тонкий, он очень противный, этот вопрос. С одной стороны, очевидно, на паре это рассказывать не нужно. С другой стороны, это важная часть языка, она должна быть задокументирована.

Я могу предложить два решения: либо добавить в конец readmi раздел "Нюансы и интересные особенности языка", который на парах будет игнорирован и оставлен на откуп любопытству, либо создать ещё одно место с документацией, что-то вроде "Language support guide", и туда документировать более энциклопедично, чем публицистически.

2024-03-30 13:31 UTC, GassaFM commented
В любом случае &mdash; этот коммит по другому поводу. Важно оставаться в рамках объявленной темы и не тащить с собой не связанные улучшения. Нужно его отсюда убрать, за-merge-ить остальное, а его при необходимости сделать отдельным PR.

2024-04-06 13:20 UTC, GassaFM requested changes
the commit https://github.com/GassaFM/interpr/pull/45/commits/5c8f7d790652292a1fbbeef667e6b13aced44c55 should be removed, the PR can be merged then

2024-04-06 14:30 UTC, merged